from __future__ import annotations

from typing import Any, Callable


def build_projects(
    *,
    C: Callable[..., dict[str, Any]],
    P: Callable[..., dict[str, str]],
    S: Callable[..., dict[str, Any]],
    metric: Callable[..., dict[str, Any]],
    bar: Callable[..., dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    return {
        "sales_management_case14_video": C(
            "方案能力不是平均培训出来的，要先养出支点",
            [
                P("zhang-lei", "zhang-lei.png", "A male new-energy sales director in his early forties, thoughtful and pragmatic posture, looking toward a customer site plan."),
                P("lin-xiao", "lin-xiao.png", "A female solution salesperson in her late twenties, curious field-observer posture, holding a blank factory notebook."),
            ],
            [
                S([1, 2], "客户要方案\n销售还在翻手册", "转型卡壳", "A new-energy sales meeting where a customer asks for an integrated solution while the salesperson nervously searches a product folder, the sales director watching the mismatch in silence.", ["客户要整体方案", "销售只会讲产品", "转型停在嘴上"], person="zhang-lei", speaker="章磊", quote="他缺的不是手册。", treatment="crisis"),
                S([3, 4], "战略说清了\n动作没有变", "半年无效", "A regional new-energy sales team listening to a strategic upgrade announcement, with product catalogues still dominating their desks and solution language floating unused in the background.", ["12人团队", "从产品到方案", "半年表现未变"], person="zhang-lei", speaker="章磊", quote="为什么一见客户还是参数和价格？", metrics=[metric("团队人数", 12, "人"), metric("转型观察", 6, "个月", tone="bad")], role="evidence", treatment="crisis"),
                S([5, 6], "标准品打法很熟\n方案客户换了考题", "能力错位", "A contrast inside an industrial park: on one side familiar product samples and price comparisons, on the other a complex factory energy system waiting to be understood.", ["市占率18%到31%", "旧打法有效三年", "工业园区要一体化方案"], person="zhang-lei", speaker="章磊", quote="题目已经换了。", metrics=[metric("区域市占率", 31, "%", from_value=18, tone="good"), metric("旧打法", 3, "年")], bars=[bar("起点市占率", 18, "%", "neutral", 35), bar("最高市占率", 31, "%", "good", 35)], role="evidence"),
                S([7, 8], "动员模板PPT\n只给了外壳", "形式到位", "A sales director places a polished solution template and presentation deck on a conference table, while blank customer-site fields remain visibly empty and untouched.", ["战略动员", "三周模板", "方案PPT改版"], person="zhang-lei", speaker="章磊", quote="格式有了，内容还没有。", metrics=[metric("模板周期", 3, "周")], nodes=["动员", "模板", "PPT", "客户现场"], links=[{"from": 1, "to": 2, "label": "配套"}, {"from": 2, "to": 3, "label": "呈现"}, {"from": 4, "to": 2, "label": "缺席"}], role="map"),
                S([9, 13], "模板被追问穿透\n空栏暴露能力缺口", "客户现场", "A chemical factory equipment director challenges a salesperson across a meeting table, while an elegant solution template lies open with empty analysis fields and the sales director realizes the real gap.", ["客户追问工况", "生产流程空白", "模板填不出方案"], person="zhang-lei", speaker="章磊", quote="模板提供的是格式。", nodes=["客户工况", "生产流程", "电费账单", "方案逻辑"], links=[{"from": 1, "to": 2, "label": "需要"}, {"from": 2, "to": 3, "label": "验证"}, {"from": 3, "to": 4, "label": "生成"}], support_beats=[{"key": "site-variables", "text": "班次、峰谷、容量\n都没有现场答案", "cueTexts": ["三班倒还是两班倒", "高峰用电", "配电容量", "每一栏都空着"], "preferredFraction": 0.42, "intent": "evidence", "purpose": "evidence", "composition": "split", "camera": "push-in"}], role="evidence", treatment="crisis"),
                S([14, 16], "三天集训及格\n现场还是空白", "课堂边界", "A classroom training scene with attentive salespeople and perfect test papers, dissolving into a factory visit where the same people face unfamiliar equipment and freeze.", ["三天集训", "测试100%及格", "客户现场接不住"], person="zhang-lei", speaker="章磊", quote="概念学会了，经验没有长出来。", metrics=[metric("课后测试", 100, "%", tone="good"), metric("集训", 3, "天")], bars=[bar("课堂理解", 100, "%", "good", 100), bar("现场把握", 35, "%", "bad", 100)], role="evidence", treatment="crisis"),
                S([17, 19], "十二人平均推\n改成三人深扎", "集中支点", "A sales director selects three curious team members from a larger group and sends them into factory floors with notebooks, while the rest of the team observes a new learning route.", ["放弃平均转型", "选出三人方案小组", "每周驻场两天"], person="lin-xiao", speaker="林晓", quote="先蹲进客户现场。", metrics=[metric("方案小组", 3, "人", tone="good"), metric("每周驻场", 2, "天", tone="good")], nodes=["林晓", "贺刚", "周蕾", "客户工厂"], links=[{"from": 1, "to": 4, "label": "驻场"}, {"from": 2, "to": 4, "label": "观察"}, {"from": 3, "to": 4, "label": "记录"}], role="map"),
                S([20, 23], "蹲到真实痛点\n方案签下420万", "现场证据", "A food processing factory cold-storage area where a solution salesperson studies energy bills and production schedules with an engineer, turning messy site evidence into a clear integrated energy plan.", ["峰谷电价差30%", "光储一体测算", "签约420万"], person="lin-xiao", speaker="林晓", quote="这次是真的知道客户在愁什么。", metrics=[metric("成本波动", 30, "%", tone="bad"), metric("签约金额", 420, "万", tone="good")], bars=[bar("峰谷波动", 30, "%", "bad", 35), bar("首单金额", 420, "万", "good", 500)], role="evidence"),
                S([24, 25], "三个内部翻译\n撬动整个团队", "团队杠杆", "A sales team gathers around three solution translators who turn factory language into company proposals, with other salespeople bringing complex customer scenarios to them.", ["内部翻译", "方案签约率8%到23%", "支点带动团队"], person="zhang-lei", speaker="章磊", quote="每个团队需要几个翻译。", metrics=[metric("方案签约率", 23, "%", from_value=8, tone="good")], bars=[bar("调整前", 8, "%", "bad", 25), bar("三个月后", 23, "%", "good", 25)], role="evidence"),
                S([26, 27], "平均用力很整齐\n支点才能出活", "销售不复杂", "A management metaphor of a small lever lifting a much larger sales team capability, with a few deeply rooted field learners becoming the pivot under warm backlight.", ["别平均用力", "先打透三个支点", "集中力量跨过能力坎"], person="zhang-lei", speaker="章磊", quote="先让少数人真正出活。", nodes=["能力断层", "集中培养", "内部翻译", "团队转型"], links=[{"from": 1, "to": 2, "label": "诊断"}, {"from": 2, "to": 3, "label": "形成"}, {"from": 3, "to": 4, "label": "撬动"}], role="metaphor"),
            ],
        ),
        "sales_management_case15_video": C(
            "培训要嵌进真实工作，反馈循环比高分课堂更重要",
            [
                P("liu-tao", "liu-tao.png", "A male franchise-development director in his late thirties, sharp but increasingly skeptical, holding a headset near a review table."),
                P("zhaoshang-guwen", "zhaoshang-guwen.png", "A young franchise consultant silhouette, seated with headset and chat messages, posture fast and practical."),
            ],
            [
                S([1, 4], "培训9.2分\n工位零使用", "高分落空", "A conference room still glowing after a popular sales training, applause fading as a franchise development team returns to their desks without using the new method.", ["满意度9.2分", "三天后无人使用", "转化率仍卡住"], person="liu-tao", speaker="刘涛", quote="评分这么高，为什么没变化？", metrics=[metric("培训评分", 9.2, "分", decimals=1, tone="good"), metric("转化率", 12, "%", tone="bad")], treatment="crisis"),
                S([5, 6], "六步成交法完整\n现场气氛热烈", "课堂成功", "A polished closed-door sales training for restaurant franchise consultants, with role-play, notebooks and confident smiles under warm stage light.", ["20万预算", "两天封闭集训", "全员考试通过"], person="liu-tao", speaker="刘涛", quote="这笔钱花得值。", metrics=[metric("培训投入", 20, "万"), metric("考试通过", 100, "%", tone="good")], bars=[bar("课堂参与", 95, "%", "good", 100), bar("当场掌握", 90, "%", "good", 100)], role="evidence"),
                S([7, 10], "七分钟电话\n走不完第一步", "场景不匹配", "A franchise consultant handles a short inquiry call while a thick training notebook lies open nearby, the ideal process much larger than the actual phone window.", ["抽听5段录音", "平均电话7分钟", "第一步要15分钟"], person="zhaoshang-guwen", speaker="招商顾问", quote="电话已经挂了，流程还没开始。", metrics=[metric("抽听录音", 5, "段"), metric("平均通话", 7, "分钟", tone="bad"), metric("第一步要求", 15, "分钟", tone="bad")], bars=[bar("真实电话", 7, "分钟", "bad", 15), bar("流程第一步", 15, "分钟", "neutral", 15)], role="evidence", treatment="crisis"),
                S([11, 12], "三百字话术\n挡不住两个字追问", "碎片沟通", "A consultant types a long carefully structured reply in a chat window while the franchise prospect responds with a short impatient question, showing a mismatch in rhythm without readable text.", ["微信碎片化", "300字回复", "加盟商只问多少"], person="zhaoshang-guwen", speaker="招商顾问", quote="客户要的是下一句。", metrics=[metric("微信回复", 300, "字", tone="bad")], role="evidence", treatment="crisis"),
                S([13, 15], "讲得越细\n越塞不进工作", "重复投入", "Two layers of training certificates and evaluation sheets pile up on a wall while the same conversion needle stays fixed, the director finally doubts the diagnosis.", ["第二次培训9.4分", "累计花费40万", "转化率仍12%"], person="liu-tao", speaker="刘涛", quote="问题不在讲得不够透。", metrics=[metric("累计投入", 40, "万", tone="bad"), metric("第二次评分", 9.4, "分", decimals=1, tone="good"), metric("转化率", 12, "%", tone="bad")], bars=[bar("培训评分", 9.4, "分", "good", 10), bar("真实转化率", 12, "%", "bad", 20)], role="evidence", treatment="crisis"),
                S([16, 18], "周五听真录音\n当场改一句话", "真实反馈", "A small franchise team gathers around a recorder on a Friday afternoon, replaying one real customer hesitation and rewriting a single practical sentence together.", ["真实录音片段", "只改一句话术", "下周立刻试"], person="liu-tao", speaker="刘涛", quote="这句话，换成你怎么接？", nodes=["真录音", "一句话术", "下周试用", "复盘结果"], links=[{"from": 1, "to": 2, "label": "提取"}, {"from": 2, "to": 3, "label": "试用"}, {"from": 3, "to": 4, "label": "验证"}], role="map"),
                S([19, 20], "每次只改一个动作\n客户开始多说", "小步落地", "A consultant changes the opening question on a phone call and later adjusts a fee discussion, with the prospect leaning in and giving more background.", ["电话多出2分钟", "报价前先确认店型", "客户主动补充信息"], person="zhaoshang-guwen", speaker="招商顾问", quote="先聊两句您那边的情况。", metrics=[metric("通话时长", 8.5, "分钟", from_value=6.5, decimals=1, tone="good")], bars=[bar("原通话", 6.5, "分钟", "bad", 9), bar("新通话", 8.5, "分钟", "good", 9)], role="evidence"),
                S([21, 23], "慢循环三个月\n转化率升到19%", "训练结果", "A simple weekly improvement loop in a busy franchise office: one call segment, one rewritten sentence, one field test, one result review, repeated until the team changes behavior.", ["每周一个动作", "三个月坚持", "转化率12%到19%"], person="liu-tao", speaker="刘涛", quote="我们有一个录音机和一个周五下午。", metrics=[metric("转化率", 19, "%", from_value=12, tone="good"), metric("新增讲师费用", 0, "元", tone="good")], bars=[bar("原转化率", 12, "%", "bad", 20), bar("三个月后", 19, "%", "good", 20)], role="evidence"),
                S([24, 26], "课堂评分是开始\n工位电话才是考场", "销售不复杂", "A closing management reflection where training notes dissolve into real customer calls and feedback loops, with the team learning directly from everyday work.", ["场景对上才落地", "真反馈形成循环", "每通电话都是考场"], person="liu-tao", speaker="刘涛", quote="学习要发生在工作里。", nodes=["课堂概念", "真实电话", "改一句话", "复盘结果"], links=[{"from": 1, "to": 2, "label": "进入"}, {"from": 2, "to": 3, "label": "改写"}, {"from": 3, "to": 4, "label": "验证"}], role="metaphor"),
            ],
        ),
        "sales_management_case16_video": C(
            "经理怕管一个人，团队会替你承担代价",
            [
                P("chen-ke", "chen-ke.png", "A female education-sales campus manager in her mid-thirties, conflicted posture, one hand near a closed office door."),
                P("liu-chang", "liu-chang.png", "A top-performing male course consultant in his early thirties, confident dominant posture, arms crossed under a sharp rim light."),
            ],
            [
                S([1, 4], "保住一个销冠\n走掉两个骨干", "公平崩塌", "A campus sales office where two reliable team members walk out through a dim doorway while a star salesperson remains in a bright central spotlight and the manager hesitates.", ["两个骨干离职", "销冠贡献三成业绩", "经理拖了半年"], person="chen-ke", speaker="陈可", quote="业绩压力我能扛，不公平我扛不住。", metrics=[metric("骨干离职", 2, "人", tone="bad"), metric("销冠贡献", 30, "%", tone="good"), metric("拖延", 6, "个月", tone="bad")], treatment="crisis"),
                S([5, 8], "能力很强\n规矩开始失效", "特权行为", "A high-performing education salesperson stands between a lead desk, an embarrassed newcomer and an empty Saturday workstation, while normal rules bend around him.", ["抢优质线索", "当众嘲讽新人", "连续周六不到岗"], person="liu-chang", speaker="刘畅", quote="业绩好像成了通行证。", nodes=["抢线索", "嘲讽新人", "考勤违规", "团队观望"], links=[{"from": 1, "to": 4, "label": "刺激"}, {"from": 2, "to": 4, "label": "压低"}, {"from": 3, "to": 4, "label": "示范"}], role="evidence", treatment="crisis"),
                S([9, 10], "她说顾全大局\n其实是在躲冲突", "自我说服", "A campus manager alone at night, holding a monthly KPI sheet like a shield while complaints from team members remain outside the closed door.", ["每月30万", "怕影响KPI", "该谈的话一推再推"], person="chen-ke", speaker="陈可", quote="他确实有本事。", metrics=[metric("月签单", 30, "万", tone="good")], nodes=["业绩依赖", "冲突恐惧", "多包容", "规则变软"], links=[{"from": 1, "to": 2, "label": "放大"}, {"from": 2, "to": 3, "label": "包装"}, {"from": 3, "to": 4, "label": "传递"}], role="metaphor"),
                S([11, 13], "第三次被抢客户\n骨干不再相信", "离职信号", "Two experienced course consultants sit in exit interviews, each leaving behind customer folders while the manager realizes complaints were treated as misunderstandings.", ["第三次反映无果", "第五个月再走一人", "保一人丢五人心"], person="chen-ke", speaker="陈可", quote="你保了一个人，丢了五个人的心。", metrics=[metric("离职骨干", 2, "人", tone="bad"), metric("反映次数", 3, "次", tone="bad")], role="evidence", treatment="crisis"),
                S([14, 15], "团队开始模仿\n新人不敢开口", "文化腐蚀", "A quiet campus sales bullpen where remaining consultants copy the star's shortcuts, newcomers lower their heads and an unanswered weekly report sits under a cold light.", ["规矩是软的", "认真守规矩吃亏", "新人学习氛围变差"], person="liu-chang", speaker="刘畅", quote="觉得氛围不好可以走。", nodes=["特权行为", "模仿扩散", "新人沉默", "团队信任下降"], links=[{"from": 1, "to": 2, "label": "示范"}, {"from": 2, "to": 3, "label": "压制"}, {"from": 3, "to": 4, "label": "侵蚀"}], role="metaphor", treatment="crisis"),
                S([16, 19], "上级算清成本\n她才看见真账", "管理成本", "A regional director confronts the campus manager with the hidden cost of losing reliable staff: recruiting, ramp-up and customer handover represented as heavy blank folders.", ["连续两个月流失", "招聘培训交接成本", "远超多签几万"], person="chen-ke", speaker="陈可", quote="你算过丢两个骨干的成本吗？", metrics=[metric("连续流失", 2, "个月", tone="bad"), metric("离职成本", 2, "骨干", tone="bad")], nodes=["招聘费", "培训期", "客户交接", "团队信任"], links=[{"from": 1, "to": 4, "label": "消耗"}, {"from": 2, "to": 4, "label": "消耗"}, {"from": 3, "to": 4, "label": "消耗"}], role="evidence"),
                S([20, 22], "关门谈三件事\n规则重新变硬", "困难对话", "A closed-door conversation where the manager calmly lays out three concrete rule violations, followed by an automatic lead assignment system and a clear attendance rule.", ["抢线索", "嘲讽新人", "考勤违规", "系统自动轮转"], person="chen-ke", speaker="陈可", quote="这三件事必须停。", metrics=[metric("签单下降", 10, "%", tone="neutral")], nodes=["事实摆出", "线索轮转", "考勤无例外", "公平恢复"], links=[{"from": 1, "to": 2, "label": "推动"}, {"from": 1, "to": 3, "label": "推动"}, {"from": 2, "to": 4, "label": "恢复"}], role="map"),
                S([23, 24], "两个月不再流失\n她承认自己怕管", "结果复盘", "A calmer campus team returns to normal work while the manager speaks with the regional director, accepting that avoiding conflict had become the real problem.", ["两个月零流失", "销冠仍是最高", "经理承认怕管"], person="chen-ke", speaker="陈可", quote="我保护的是自己不用面对冲突。", metrics=[metric("后续流失", 0, "人", tone="good"), metric("观察期", 2, "个月", tone="good")], bars=[bar("调整前流失", 2, "人", "bad", 2), bar("调整后流失", 0, "人", "good", 2)], role="evidence"),
                S([25, 26], "沉默每天都在投票\n公平比一个销冠更贵", "销售不复杂", "A closing metaphor where one bright star casts a long shadow over a team scale, and the manager finally balances performance with fairness under a warm backlight.", ["规则不能软", "别让团队替你忍", "信任比短期业绩更贵"], person="chen-ke", speaker="陈可", quote="怕得罪一个人，会丢掉一群人的心。", nodes=["逃避对话", "规则变软", "骨干离开", "信任流失"], links=[{"from": 1, "to": 2, "label": "导致"}, {"from": 2, "to": 3, "label": "推动"}, {"from": 3, "to": 4, "label": "造成"}], role="metaphor"),
            ],
        ),
        "sales_management_case17_video": C(
            "没有处方权，也能用小试点松动规则",
            [
                P("zheng-weiguo", "zheng-weiguo.png", "A male regional engineering-sales manager in his late forties, steady field-experienced posture, holding a rejected proposal folder."),
                P("customer-director", "customer-director.png", "A male industrial infrastructure director silhouette, firm customer posture, standing beside a construction site window."),
            ],
            [
                S([1, 4], "方案写了三次\n总部都没批", "处方权缺失", "A regional manager sits before three rejected incentive reform proposals, with headquarters replies glowing coldly on a distant screen and a construction market map behind him.", ["三份改革方案", "一次都没批准", "问题看得见"], person="zheng-weiguo", speaker="郑卫国", quote="方向盘不在我手上。", metrics=[metric("被驳回方案", 3, "次", tone="bad"), metric("团队销售", 40, "人")], treatment="crisis"),
                S([5, 8], "规则只奖励新签\n客户关系被透支", "激励错位", "An engineering sales pipeline where new contracts shine in front while project delivery, customer satisfaction and renewal folders fade into shadow after handoff.", ["续约口碑占40%+", "满意度六季下滑", "续约率72%到58%"], person="zheng-weiguo", speaker="郑卫国", quote="签完就走，后面没人管。", metrics=[metric("续约率", 58, "%", from_value=72, tone="bad"), metric("续约口碑营收", 40, "%+", tone="good")], bars=[bar("原续约率", 72, "%", "good", 80), bar("当前续约率", 58, "%", "bad", 80)], role="evidence", treatment="crisis"),
                S([9, 13], "第一次讲增长\n第二次卡预算", "两次碰壁", "A manager sends reform reports upward through a tall headquarters building, each report returning smaller and colder while lost renewal customers accumulate at the regional office.", ["2023年9月首提", "三个月丢两家", "新增奖金被驳回"], person="zheng-weiguo", speaker="郑卫国", quote="看得见悬崖，方向盘不在手上。", metrics=[metric("等待", 3, "个月", tone="bad"), metric("续约大客户流失", 2, "家", tone="bad")], role="evidence", treatment="crisis"),
                S([14, 15], "八百万客户流失\n因果链终于具体", "案例证据", "An industrial client chooses a competitor while the regional manager reconstructs the full loss chain: overpromising, strained delivery, complaint, claim and failed renewal.", ["年度合同800万+", "销售过度承诺", "交付差导致流失"], person="customer-director", speaker="客户基建总监", quote="对面销售每个月来一次。", metrics=[metric("流失合同", 800, "万+", tone="bad")], nodes=["新签激励", "过度承诺", "交付落差", "客户流失"], links=[{"from": 1, "to": 2, "label": "推高"}, {"from": 2, "to": 3, "label": "造成"}, {"from": 3, "to": 4, "label": "导致"}], role="evidence", treatment="crisis"),
                S([16, 17], "全面改革批不了\n先拿半年试点", "缝隙设计", "A headquarters approval gate opens only a narrow slot, and the regional manager reshapes a broad reform proposal into a contained six-month pilot inside existing commission limits.", ["半年试点", "不动总提成比例", "15%挂钩满意度"], person="zheng-weiguo", speaker="郑卫国", quote="先缩小到没人反对。", metrics=[metric("试点周期", 6, "个月", tone="good"), metric("挂钩比例", 15, "%", tone="good")], nodes=["总部边界", "试点空间", "满意度评分", "提成发放"], links=[{"from": 1, "to": 2, "label": "留下"}, {"from": 2, "to": 3, "label": "绑定"}, {"from": 3, "to": 4, "label": "影响"}], role="map"),
                S([18, 19], "承诺开始有后果\n行为马上变了", "规则生效", "Several engineering salespeople approach the manager with worried questions after realizing their bid promises will be scored by customers three months later.", ["三个月后客户评分", "不达标扣15%", "销售开始谨慎承诺"], person="zheng-weiguo", speaker="郑卫国", quote="三个月后客户来评分。", metrics=[metric("扣减比例", 15, "%", tone="neutral"), metric("评分延迟", 3, "个月")], role="evidence"),
                S([20, 21], "满意度回升11点\n总部开始推广", "试点事实", "A regional performance review with customer satisfaction rising and renewal rate recovering, while headquarters opens the same pilot to two other regions.", ["满意度回升11点", "续约率58%到67%", "推广到两个大区"], person="zheng-weiguo", speaker="郑卫国", quote="结果把规则松动了。", metrics=[metric("满意度回升", 11, "点", tone="good"), metric("续约率", 67, "%", from_value=58, tone="good"), metric("推广大区", 2, "个", tone="good")], bars=[bar("试点前续约率", 58, "%", "bad", 70), bar("试点后续约率", 67, "%", "good", 70)], role="evidence"),
                S([22, 24], "改不了规则\n先制造局部事实", "销售不复杂", "A closing metaphor of a manager driving through a narrow side road beside a blocked highway, bringing visible results back toward the larger headquarters system.", ["缩小方案", "局部试点", "用结果松动规则"], person="zheng-weiguo", speaker="郑卫国", quote="先找到能自己踩油门的小路。", nodes=["没有处方权", "找到缝隙", "做出事实", "反推规则"], links=[{"from": 1, "to": 2, "label": "转向"}, {"from": 2, "to": 3, "label": "试点"}, {"from": 3, "to": 4, "label": "松动"}], role="metaphor"),
            ],
        ),
        "sales_management_case18_video": C(
            "管理者要定期回到信息产生的地方",
            [
                P("fang-hongyuan", "fang-hongyuan.png", "A male advertising commercialization director in his early forties, experienced but surprised, one hand near a silent phone."),
                P("customer-leader", "customer-leader.png", "A senior platform advertising leader silhouette, direct posture at a high-level meeting table."),
            ],
            [
                S([1, 3], "每个决策都对\n只是晚了三个月", "信息迟滞", "A senior advertising director sits in a high-level meeting as a partner's blunt feedback cuts through polished reports, the room suddenly still.", ["合作伙伴当面质疑", "总监最后知道真相", "判断比市场晚一拍"], person="fang-hongyuan", speaker="方宏远", quote="这个情况我需要回去确认。", treatment="crisis"),
                S([4, 5], "他以前判断很准\n管理方式也很稳", "旧能力可靠", "A confident advertising salesperson turned director reviews accounts through weekly reviews, monthly calls and quarterly strategy meetings, the system appearing orderly and competent.", ["八年广告销售", "千万级客户经验", "固定Review机制"], person="fang-hongyuan", speaker="方宏远", quote="这套方式前两年很好用。", metrics=[metric("广告销售经验", 8, "年"), metric("大客户投放", 1000, "万+", tone="good")], role="evidence"),
                S([6, 9], "周报磨平棱角\n数据天然滞后", "信息滤镜", "A director drives with an old folded map while layered weekly reports, review dashboards and presentation pages filter raw market signals before they reach him.", ["周报包装坏消息", "Review滞后三个月", "三个月前地图开车"], person="fang-hongyuan", speaker="方宏远", quote="每个转弯都正确，路已经变了。", metrics=[metric("信息滞后", 3, "个月", tone="bad")], nodes=["周报", "Review", "PPT", "真实市场"], links=[{"from": 4, "to": 1, "label": "过滤"}, {"from": 1, "to": 2, "label": "汇总"}, {"from": 2, "to": 3, "label": "再包装"}], role="metaphor", treatment="crisis"),
                S([10, 13], "一线信号被旧结论压住\n三个客户被拿走", "早期预警", "A senior salesperson quietly brings a new performance-based advertising signal, but the director pushes it aside with an old conclusion while competitors approach key clients.", ["客户问效果付费", "三年前结论否定", "三个大客户流失"], person="fang-hongyuan", speaker="方宏远", quote="ROI模型跑不通。", metrics=[metric("流失客户", 3, "个", tone="bad"), metric("单客年度投放", 500, "万+", tone="bad")], role="evidence", treatment="crisis"),
                S([14, 18], "高层会被点醒\n三通电话见真相", "真相冲击", "A platform advertising leader challenges the director across a boardroom table, followed by three direct customer phone calls revealing competitor terms, neglected service and stale proposals.", ["竞品谈效果分账", "分账15%到20%", "两个月没人拜访"], person="customer-leader", speaker="合作伙伴负责人", quote="你知道吗？", metrics=[metric("分账比例", 20, "%", from_value=15, tone="bad"), metric("客户空窗", 2, "个月", tone="bad")], nodes=["竞品分账", "客户空窗", "方案陈旧", "周报未提"], links=[{"from": 1, "to": 4, "label": "缺失"}, {"from": 2, "to": 4, "label": "缺失"}, {"from": 3, "to": 4, "label": "缺失"}], role="evidence", treatment="crisis"),
                S([19, 21], "每月两天跑客户\n只带耳朵", "回到一线", "The director visits customers without subordinates, listening quietly in offices and bringing back raw unexpected feedback that changes the team's reporting habit.", ["每月两天一线日", "不带下属不谈签单", "周报新增意外反馈"], person="fang-hongyuan", speaker="方宏远", quote="我得自己去听原文。", metrics=[metric("一线日", 2, "天/月", tone="good")], nodes=["客户原话", "竞品报告", "意外反馈", "决策输入"], links=[{"from": 1, "to": 4, "label": "进入"}, {"from": 2, "to": 4, "label": "补充"}, {"from": 3, "to": 4, "label": "校正"}], role="map"),
                S([22, 23], "产品重新立项\n半年拿回客户", "判断修复", "A commercialization director uses firsthand market notes to restart a performance-based advertising product discussion, with two previously lost customers returning into the light.", ["三个月推动立项", "半年拿回两家客户", "加工信息变原始信号"], person="fang-hongyuan", speaker="方宏远", quote="我知道的全是加工过的信息。", metrics=[metric("立项周期", 3, "个月", tone="good"), metric("拿回客户", 2, "家", tone="good")], bars=[bar("流失客户", 3, "家", "bad", 3), bar("拿回客户", 2, "家", "good", 3)], role="evidence"),
                S([24, 26], "别拿旧地图开新路\n定期回到信息源", "销售不复杂", "A closing metaphor of a director replacing an outdated map with raw customer voices, reconnecting headquarters decisions to the place where market information is born.", ["周报会翻译", "Review会滞后", "亲自听原文"], person="fang-hongyuan", speaker="方宏远", quote="信息产生在哪里，就回到哪里。", nodes=["真实市场", "一线原文", "管理判断", "及时调整"], links=[{"from": 1, "to": 2, "label": "产生"}, {"from": 2, "to": 3, "label": "校正"}, {"from": 3, "to": 4, "label": "推动"}], role="metaphor"),
            ],
        ),
        "sales_management_case19_video": C(
            "管理者也需要意义补给，方向感比加压更能续航",
            [
                P("qian-shaohua", "qian-shaohua.png", "A male high-end manufacturing sales director in his mid-forties, once energetic but visibly drained, standing near a blank whiteboard."),
                P("zhao-chen", "zhao-chen.png", "A senior male group sales VP silhouette, calm and observant, leaning forward in a quiet dinner conversation."),
            ],
            [
                S(
                    [1, 4],
                    "动作都还在\n团队却失去方向",
                    "隐性熄火",
                    "A manufacturing sales director continues signing papers and holding reviews, but the team around him senses the light has dimmed and the direction is unclear.",
                    ["所有流程还在", "团队感觉不对", "九点八亿新目标"],
                    person="qian-shaohua",
                    speaker="钱少华",
                    quote="大家觉得老大自己不信了。",
                    metrics=[metric("年营收目标", 9.8, "亿", tone="good"), metric("团队规模", 40, "人")],
                    support_beats=[
                        {
                            "key": "correct-actions-lost-direction",
                            "text": "动作都正确\n方向感却在下降",
                            "cueTexts": ["所有正确事情", "慢慢失去方向感", "九点八个亿", "再涨百分之四十"],
                            "preferredFraction": 0.9,
                            "intent": "decision",
                            "purpose": "escalate",
                            "composition": "split",
                            "camera": "push-in",
                        }
                    ],
                    treatment="crisis",
                ),
                S([5, 7], "过去他是发动机\n第四年细节变了", "能量对比", "A sales leader once drawing strategy on a whiteboard for an energized manufacturing team, contrasted with a later meeting where he reads from slides mechanically.", ["三年每年增长40%+", "白板讲40分钟", "第四年只照PPT念"], person="qian-shaohua", speaker="钱少华", quote="跟着钱总干，方向不会错。", metrics=[metric("连续增长", 3, "年", tone="good"), metric("白板讲解", 40, "分钟", tone="good")], bars=[bar("第一年增长", 40, "%", "good", 45), bar("第二年增长", 41, "%", "good", 45), bar("第三年增长", 43, "%", "good", 45)], role="evidence"),
                S([8, 11], "客户不去了\n问题不追了", "信号扩散", "A set of small management signals: an empty customer visit seat, a repeated quarterly slide deck and an important project update receiving only a one-word response.", ["两个月没见客户", "动员内容重复", "重要项目只说行"], person="qian-shaohua", speaker="钱少华", quote="这些小事合起来很重。", metrics=[metric("客户现场空窗", 2, "个月", tone="bad")], nodes=["不去客户现场", "照念PPT", "不再追问", "团队感受"], links=[{"from": 1, "to": 4, "label": "传递"}, {"from": 2, "to": 4, "label": "传递"}, {"from": 3, "to": 4, "label": "传递"}], role="evidence", treatment="crisis"),
                S([12, 13], "每年再加40%\n意义电池被耗空", "动力耗尽", "A drained sales director running on a long straight treadmill of repeated forty-percent targets, with each completed milestone immediately replaced by another identical one.", ["完成又加目标", "每年消耗30%", "三年后油箱空了"], person="qian-shaohua", speaker="钱少华", quote="我不知道在为什么跑。", metrics=[metric("年度加压", 40, "%", tone="bad"), metric("年消耗", 30, "%", tone="bad"), metric("年补回", 20, "%", tone="neutral")], bars=[bar("消耗", 30, "%", "bad", 40), bar("补给", 20, "%", "neutral", 40)], role="metaphor", treatment="crisis"),
                S([14, 17], "总监熄火\n系统节奏一起慢", "状态传染", "A regional sales system slows down in layers: directors visit less, managers step back and frontline customer visits decline while a quarterly review misses target.", ["大区经理跟着降频", "基层拜访下降15%", "一季度完成82%"], person="qian-shaohua", speaker="钱少华", quote="像是在完成任务。", metrics=[metric("拜访量下降", 15, "%", tone="bad"), metric("一季度完成", 82, "%", tone="bad")], bars=[bar("目标", 100, "%", "neutral", 100), bar("实际完成", 82, "%", "bad", 100), bar("拜访下降", 15, "%", "bad", 100)], role="evidence", treatment="crisis"),
                S([18, 21], "上级没有加压\n先让他去看未来", "意义补给", "A quiet dinner conversation between the group VP and the drained sales director, followed by a contemplative trip to Japanese industry benchmark customers with no sales agenda.", ["直接问状态", "两周日本标杆", "不带客户名单"], person="zhao-chen", speaker="赵晨", quote="别谈业务，就去看看。", metrics=[metric("标杆拜访", 2, "家", tone="good"), metric("外出时间", 2, "周", tone="good")], nodes=["直接提问", "停止说教", "行业标杆", "重新看路"], links=[{"from": 1, "to": 2, "label": "代替"}, {"from": 2, "to": 3, "label": "安排"}, {"from": 3, "to": 4, "label": "打开"}], role="map"),
                S([22, 25], "看到下一条路\n白板又回来了", "方向重燃", "A manufacturing sales director returns from Japan with a thick notebook, drawing future industry paths on a whiteboard while the team sees his energy come back.", ["12页笔记", "未来不止20%", "白板画了40分钟"], person="qian-shaohua", speaker="钱少华", quote="白板又回来了。", metrics=[metric("飞行笔记", 12, "页", tone="good"), metric("白板分享", 40, "分钟", tone="good")], nodes=["更高精度标准", "数字孪生维护", "产品线重设", "团队方向"], links=[{"from": 1, "to": 3, "label": "推动"}, {"from": 2, "to": 3, "label": "打开"}, {"from": 3, "to": 4, "label": "点亮"}], role="evidence"),
                S([26, 28], "管理者油箱也会空\n意义感就是燃料", "销售不复杂", "A closing management metaphor where a leader's internal fuel tank is refilled by a visible future road, warming the entire team's temperature again.", ["员工熄火影响一人", "经理熄火影响团队", "意义补给比加压更有效"], person="qian-shaohua", speaker="钱少华", quote="找到下一步去哪，比再加一把劲更重要。", nodes=["高压增长", "意义耗尽", "看到未来", "团队升温"], links=[{"from": 1, "to": 2, "label": "消耗"}, {"from": 3, "to": 2, "label": "补给"}, {"from": 3, "to": 4, "label": "带动"}], role="metaphor"),
            ],
        ),
    }
